[package]
name = "mini_portainer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
anyhow = "1.0.93"
env_logger = "0.11.5"
log = "0.4.22"
serde = "1.0.215"
serde_json = "1.0.132"
tokio-postgres = "0.7.12"
